#!/bin/bash

if [[ -z "$@" ]] ; then echo "Need arguments." ; exit 1 ; fi
      
while [ $# -gt 0 ]
do    
  case "$(tr '[:upper:]' '[:lower:]'<<<$1)" in
    -remote)
      remote="$2"
      shift
    ;;
    -attachment)
      attachment="$2"
      shift
    ;;
    -to)
      to="$2"
      shift
    ;;
    -from)
      from="$2"
      shift
    ;;
   -subject)
      subject="$2"
      shift
    ;;
   -body)
      body="$2"
      shift
    ;;
  esac
  shift
done

if [ -z "${remote}" ] || [ -z "${to}" ] || [ -z "${from}" ] || [ -z "${subject}" ] || [ -z "${body}" ]
then
  echo "Core arguments must be provided: -remote -to -from -subject -body"
  exit 1
fi

if [ -n "${attachment}" ]
then
  attachmentBase64=$(base64 < ${attachment})
  attachmentFilename=$(basename ${attachment})
fi

rawEml=''
rawEml+="To: ${to}"$'\n'
rawEml+="From: ${from}"$'\n'
rawEml+="Subject: ${subject}"$'\n'
rawEml+="MIME-Version: 1.0"$'\n'
rawEml+="Content-Type: multipart/mixed; boundary=\"X-=-=-=-text boundary\""$'\n'
#rawEml+=$'\n'
#rawEml+="--X-=-=-=-text boundary"$'\n'
#rawEml+="Content-Type: text/plain"$'\n'
#rawEml+=$'\n'
#rawEml+="${body}"$'\n'
#rawEml+=$'\n'
if [ -n "${attachment}" ]
then
  rawEml+="--X-=-=-=-text boundary"$'\n'
  rawEml+="Content-Type: text/csv; name=\"${attachmentFilename}\""$'\n'
  rawEml+="Content-Transfer-Encoding: base64"$'\n'
  rawEml+="Content-Disposition: attachment; filename=\"${attachmentFilename}\""$'\n'
  rawEml+=$'\n'
  rawEml+="${attachmentBase64}"$'\n'
  rawEml+="--X-=-=-=-text boundary"$'\n'
fi

if [ -n "${tls}" ]
then
  echo "Using openssl and -starttls smtp + -crlf"
  command="openssl s_client -connect ${remote}:25 -starttls smtp -crlf"
else
  command="telnet ${remote} 25"
fi

{ echo "ehlo mecrla001.middys.local";
 echo "mail from: ${from}";
 echo "rcpt to: ${to}";
 echo "data";
 echo "${rawEml}";
 echo ".";
 echo "quit";
 sleep 1;
} | telnet $remote 25
